// Code generated by mockery v2.52.1. DO NOT EDIT.

package auth_proto

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthClient is an autogenerated mock type for the AuthClient type
type MockAuthClient struct {
	mock.Mock
}

type MockAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthClient) EXPECT() *MockAuthClient_Expecter {
	return &MockAuthClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *MockAuthClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *LoginRequest, ...grpc.CallOption) (*LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *LoginRequest, ...grpc.CallOption) *LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthClient_Login_Call {
	return &MockAuthClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthClient_Login_Call) Run(run func(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption)) *MockAuthClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockAuthClient_Login_Call) Return(_a0 *LoginResponse, _a1 error) *MockAuthClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthClient_Login_Call) RunAndReturn(run func(context.Context, *LoginRequest, ...grpc.CallOption) (*LoginResponse, error)) *MockAuthClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthClient creates a new instance of MockAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthClient {
	mock := &MockAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
