// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/gei/gei.proto

package indexer_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ScheduleJson  string                 `protobuf:"bytes,2,opt,name=schedule_json,json=scheduleJson,proto3" json:"schedule_json,omitempty"` // The schedule data as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreScheduleRequest) Reset() {
	*x = StoreScheduleRequest{}
	mi := &file_internal_proto_gei_gei_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreScheduleRequest) ProtoMessage() {}

func (x *StoreScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_gei_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreScheduleRequest.ProtoReflect.Descriptor instead.
func (*StoreScheduleRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_gei_proto_rawDescGZIP(), []int{0}
}

func (x *StoreScheduleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StoreScheduleRequest) GetScheduleJson() string {
	if x != nil {
		return x.ScheduleJson
	}
	return ""
}

type StoreScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreScheduleResponse) Reset() {
	*x = StoreScheduleResponse{}
	mi := &file_internal_proto_gei_gei_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreScheduleResponse) ProtoMessage() {}

func (x *StoreScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_gei_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreScheduleResponse.ProtoReflect.Descriptor instead.
func (*StoreScheduleResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_gei_proto_rawDescGZIP(), []int{1}
}

func (x *StoreScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreScheduleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_internal_proto_gei_gei_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_gei_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_gei_proto_rawDescGZIP(), []int{2}
}

func (x *GetScheduleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ScheduleJson  string                 `protobuf:"bytes,2,opt,name=schedule_json,json=scheduleJson,proto3" json:"schedule_json,omitempty"` // The decrypted schedule data
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_internal_proto_gei_gei_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_gei_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_gei_proto_rawDescGZIP(), []int{3}
}

func (x *GetScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetScheduleResponse) GetScheduleJson() string {
	if x != nil {
		return x.ScheduleJson
	}
	return ""
}

func (x *GetScheduleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_gei_gei_proto protoreflect.FileDescriptor

const file_internal_proto_gei_gei_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/gei/gei.proto\x12\x11grpc.gei.schedule\"W\n" +
	"\x14StoreScheduleRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rschedule_json\x18\x02 \x01(\tR\fscheduleJson\"K\n" +
	"\x15StoreScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x12GetScheduleRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"n\n" +
	"\x13GetScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rschedule_json\x18\x02 \x01(\tR\fscheduleJson\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xd3\x01\n" +
	"\x0fScheduleIndexer\x12b\n" +
	"\rStoreSchedule\x12'.grpc.gei.schedule.StoreScheduleRequest\x1a(.grpc.gei.schedule.StoreScheduleResponse\x12\\\n" +
	"\vGetSchedule\x12%.grpc.gei.schedule.GetScheduleRequest\x1a&.grpc.gei.schedule.GetScheduleResponseB,Z*github.com/nrmnqdds/gomaluum/indexer_protob\x06proto3"

var (
	file_internal_proto_gei_gei_proto_rawDescOnce sync.Once
	file_internal_proto_gei_gei_proto_rawDescData []byte
)

func file_internal_proto_gei_gei_proto_rawDescGZIP() []byte {
	file_internal_proto_gei_gei_proto_rawDescOnce.Do(func() {
		file_internal_proto_gei_gei_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gei_gei_proto_rawDesc), len(file_internal_proto_gei_gei_proto_rawDesc)))
	})
	return file_internal_proto_gei_gei_proto_rawDescData
}

var file_internal_proto_gei_gei_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_gei_gei_proto_goTypes = []any{
	(*StoreScheduleRequest)(nil),  // 0: grpc.gei.schedule.StoreScheduleRequest
	(*StoreScheduleResponse)(nil), // 1: grpc.gei.schedule.StoreScheduleResponse
	(*GetScheduleRequest)(nil),    // 2: grpc.gei.schedule.GetScheduleRequest
	(*GetScheduleResponse)(nil),   // 3: grpc.gei.schedule.GetScheduleResponse
}
var file_internal_proto_gei_gei_proto_depIdxs = []int32{
	0, // 0: grpc.gei.schedule.ScheduleIndexer.StoreSchedule:input_type -> grpc.gei.schedule.StoreScheduleRequest
	2, // 1: grpc.gei.schedule.ScheduleIndexer.GetSchedule:input_type -> grpc.gei.schedule.GetScheduleRequest
	1, // 2: grpc.gei.schedule.ScheduleIndexer.StoreSchedule:output_type -> grpc.gei.schedule.StoreScheduleResponse
	3, // 3: grpc.gei.schedule.ScheduleIndexer.GetSchedule:output_type -> grpc.gei.schedule.GetScheduleResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_gei_gei_proto_init() }
func file_internal_proto_gei_gei_proto_init() {
	if File_internal_proto_gei_gei_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gei_gei_proto_rawDesc), len(file_internal_proto_gei_gei_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gei_gei_proto_goTypes,
		DependencyIndexes: file_internal_proto_gei_gei_proto_depIdxs,
		MessageInfos:      file_internal_proto_gei_gei_proto_msgTypes,
	}.Build()
	File_internal_proto_gei_gei_proto = out.File
	file_internal_proto_gei_gei_proto_goTypes = nil
	file_internal_proto_gei_gei_proto_depIdxs = nil
}
