// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package indexer_proto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei(in *jlexer.Lexer, out *StoreScheduleResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei(out *jwriter.Writer, in StoreScheduleResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Success {
		const prefix string = ",\"success\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.Success))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StoreScheduleResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StoreScheduleResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StoreScheduleResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StoreScheduleResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei(l, v)
}
func easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei1(in *jlexer.Lexer, out *StoreScheduleRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "schedule_json":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScheduleJson = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei1(out *jwriter.Writer, in StoreScheduleRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Username != "" {
		const prefix string = ",\"username\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	if in.ScheduleJson != "" {
		const prefix string = ",\"schedule_json\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ScheduleJson))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StoreScheduleRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StoreScheduleRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StoreScheduleRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StoreScheduleRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei1(l, v)
}
func easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei2(in *jlexer.Lexer, out *GetScheduleResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		case "schedule_json":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScheduleJson = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei2(out *jwriter.Writer, in GetScheduleResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Success {
		const prefix string = ",\"success\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.Success))
	}
	if in.ScheduleJson != "" {
		const prefix string = ",\"schedule_json\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ScheduleJson))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetScheduleResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetScheduleResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetScheduleResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetScheduleResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei2(l, v)
}
func easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei3(in *jlexer.Lexer, out *GetScheduleRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei3(out *jwriter.Writer, in GetScheduleRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Username != "" {
		const prefix string = ",\"username\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetScheduleRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetScheduleRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAf2c14d3EncodeGithubComNrmnqddsGomaluumInternalProtoGei3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetScheduleRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetScheduleRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAf2c14d3DecodeGithubComNrmnqddsGomaluumInternalProtoGei3(l, v)
}
