// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: internal/proto/gei/gei.proto

package indexer_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScheduleIndexer_StoreSchedule_FullMethodName = "/grpc.gei.schedule.ScheduleIndexer/StoreSchedule"
	ScheduleIndexer_GetSchedule_FullMethodName   = "/grpc.gei.schedule.ScheduleIndexer/GetSchedule"
)

// ScheduleIndexerClient is the client API for ScheduleIndexer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScheduleIndexer service for storing and retrieving user schedules
type ScheduleIndexerClient interface {
	// Store a user's schedule (will be encrypted)
	StoreSchedule(ctx context.Context, in *StoreScheduleRequest, opts ...grpc.CallOption) (*StoreScheduleResponse, error)
	// Retrieve a user's schedule (will be decrypted)
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error)
}

type scheduleIndexerClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleIndexerClient(cc grpc.ClientConnInterface) ScheduleIndexerClient {
	return &scheduleIndexerClient{cc}
}

func (c *scheduleIndexerClient) StoreSchedule(ctx context.Context, in *StoreScheduleRequest, opts ...grpc.CallOption) (*StoreScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleIndexer_StoreSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleIndexerClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleIndexer_GetSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleIndexerServer is the server API for ScheduleIndexer service.
// All implementations must embed UnimplementedScheduleIndexerServer
// for forward compatibility.
//
// ScheduleIndexer service for storing and retrieving user schedules
type ScheduleIndexerServer interface {
	// Store a user's schedule (will be encrypted)
	StoreSchedule(context.Context, *StoreScheduleRequest) (*StoreScheduleResponse, error)
	// Retrieve a user's schedule (will be decrypted)
	GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error)
	mustEmbedUnimplementedScheduleIndexerServer()
}

// UnimplementedScheduleIndexerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduleIndexerServer struct{}

func (UnimplementedScheduleIndexerServer) StoreSchedule(context.Context, *StoreScheduleRequest) (*StoreScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreSchedule not implemented")
}
func (UnimplementedScheduleIndexerServer) GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchedule not implemented")
}
func (UnimplementedScheduleIndexerServer) mustEmbedUnimplementedScheduleIndexerServer() {}
func (UnimplementedScheduleIndexerServer) testEmbeddedByValue()                         {}

// UnsafeScheduleIndexerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleIndexerServer will
// result in compilation errors.
type UnsafeScheduleIndexerServer interface {
	mustEmbedUnimplementedScheduleIndexerServer()
}

func RegisterScheduleIndexerServer(s grpc.ServiceRegistrar, srv ScheduleIndexerServer) {
	// If the following call pancis, it indicates UnimplementedScheduleIndexerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduleIndexer_ServiceDesc, srv)
}

func _ScheduleIndexer_StoreSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleIndexerServer).StoreSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleIndexer_StoreSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleIndexerServer).StoreSchedule(ctx, req.(*StoreScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleIndexer_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleIndexerServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleIndexer_GetSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleIndexerServer).GetSchedule(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleIndexer_ServiceDesc is the grpc.ServiceDesc for ScheduleIndexer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleIndexer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gei.schedule.ScheduleIndexer",
	HandlerType: (*ScheduleIndexerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreSchedule",
			Handler:    _ScheduleIndexer_StoreSchedule_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _ScheduleIndexer_GetSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/gei/gei.proto",
}
