name: Deploy Images to Digital Ocean
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: latest
      #     args: --config=./.golangci.yaml --timeout=30m --verbose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nrmnqdds
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/nrmnqdds/gomaluum:latest
          cache-from: type=registry,ref=ghcr.io/nrmnqdds/gomaluum:cache
          cache-to: type=registry,mode=max,ref=ghcr.io/nrmnqdds/gomaluum:cache,image-manifest=true
  deploy:
    needs: push-store-image
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Deploy to Digital Ocean'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u nrmnqdds -p ${{ secrets.GHCR_TOKEN }}
            docker compose pull
            docker compose up --force-recreate --build -d gomaluum
            docker system prune -a -f
